modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/JustDoom/Dont-Run-With-Scissors/issues"
license = "MIT"

[[mods]]
modId = "dontrunwithscissors"
version = "${version}"
displayName = "Dont Run With Scissors"
authors = "JustDoom"
description = '''
Running with scissors is dangerous, even in Minecraft
'''
logoFile = "logo.png"

[[dependencies.dontrunwithscissors]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dontrunwithscissors]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"