modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/JustDoom/Dont-Run-With-Scissors/issues"
license = "MIT"

[[mods]]
modId = "dontrunwithscissors"
version = "${version}"
displayName = "Dont Run With Scissors"
authors = "JustDoom"
description = '''
Running with scissors is dangerous, even in Minecraft
'''
logoFile = "logo.png"

[[dependencies.dontrunwithscissors]]
modId = "neoforge"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dontrunwithscissors]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "dontrunwithscissors-common.mixins.json"